/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package permisos.gui;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import permisos.gui.logica.LoginLogic;
import permisos.utilitario.ErrorBD;

/**
 *
 * @author Kevin Camilo Gómez González - kgomezg81832@universidadean.edu.co
 */
public class frmLogin extends javax.swing.JFrame {

    private static final LoginLogic ll = new LoginLogic();
    private static final frmInicio frmIni = new frmInicio();

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();

        // Agrego validación de cerrar sesión.
        frmLogin.this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                Object[] opciones = {"Aceptar", "Cancelar"};

                if (JOptionPane.showOptionDialog(
                        frmLogin.this, "Señor(a) Usuario(a):\n¿Está seguro de cerrar la aplicación?\nSi lo esta de click en Aceptar de lo contrario de click en Cancelar", "Confirmación",
                        0, JOptionPane.INFORMATION_MESSAGE, null, opciones, null) == 0) {
                    System.exit(0);
                }
            }
        });
    }

    public void init() {
        setVisible(true);
    }

    public void desinit() {
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inUsuario = new javax.swing.JTextField();
        lbUsuario = new javax.swing.JLabel();
        lbClave = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        inClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesión");
        setName("Login"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        inUsuario.setToolTipText("Introduzca el usuario");

        lbUsuario.setText("Usuario:");
        lbUsuario.setToolTipText("");

        lbClave.setText("Clave:");

        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setToolTipText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inClave)
                    .addComponent(inUsuario, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbUsuario)
                            .addComponent(lbClave))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lbClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String usuario = inUsuario.getText(), clave = inClave.getText();

        if (usuario.length() == 0 && clave.length() == 0) {
            JOptionPane.showMessageDialog(null, "Señor(a) Usuario(a): Diligencie un usuario y clave e intente de nuevo.");
        } else if (usuario.length() == 0) {
            JOptionPane.showMessageDialog(null, "Señor(a) Usuario(a): Diligencie un usuario e intente de nuevo.");
        } else if (clave.length() == 0) {
            JOptionPane.showMessageDialog(null, "Señor(a) Usuario(a): Diligencie una clave e intente de nuevo.");
        } else {
            try {
                int IdUsuario = ll.existeLogin(inUsuario.getText(), inClave.getText());

                if (IdUsuario > 0) {
                    desinit();
                    frmIni.init(IdUsuario);
                } else {
                    JOptionPane.showMessageDialog(null, "Señor(a) Usuario(a): Usuario / Contraseña incorrecta, verifique la información diligenciada.");
                }

            } catch (HeadlessException ex) {
                ErrorBD ebd = new ErrorBD(ex.getClass().toString(), ex.getCause().toString(), ex.getMessage());
            }
        }

    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JPasswordField inClave;
    private javax.swing.JTextField inUsuario;
    private javax.swing.JLabel lbClave;
    private javax.swing.JLabel lbUsuario;
    // End of variables declaration//GEN-END:variables
}
